[package]
name = "fuzzy_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
float-cmp = "0.9.0"

[dependencies]
plotters = "0.3.4"
rayon = "1.7.0"
