[package]
name = "tech_indicators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.6.1"
serde = { version = "1.0.152", features = ["derive"] }

[dev-dependencies]
float-cmp = "0.9.0"
